### ISSUE TITLE
Select single feature out of an enhanced selection is not possible 

### ISSUE THREAD

**Issue by marikemau** [conterra/mapapps-enhanced-selection#13]
Right now, it is not possible to click through the selected features and get information from the result center similar to the selection bundle. In the selection bundle in combination with the result center bundle the user can click on a single feature (for example out of the freehand polygon selection) and the selected feature is highlighted in the result center. For the user it would be nice to have a similar behavior for the enhanced selection.

**Comment by matthiasstein** [comment]
This bundle is deprecated.
