### ISSUE TITLE
Possibility to delete the "within" option

### ISSUE THREAD

**Issue by StefanMenze** [conterra/mapapps-enhanced-selection#4]
It is known that distance selection doesn't work correctly in combination with the spatial relationship "within". Is it possible to delete this option in the app.json?

**Comment by matthiasstein** [comment]
I published a new release [v2.0.3](https://github.com/conterra/mapapps-enhanced-selection/releases/tag/v2.0.3). Now it is possible to disable the "within" function in the app.json.

You need to add the following code to the dn_enhancedselection-settings in your app.json:

```
"BaseWidget": {
  "enableContains": false
}
```
